### PR TITLE
(PUP-5662)Specify that hash has keys in insertion order

### PR DESCRIPTION
**Pull request by hlindberg**

### CODE REVIEW

**Comment by peterhuene** [comment]
:+1:

**Comment by peterhuene** [comment]
Looks like there's this in `expressions.md`

> When matching against a Hash the keys are searched in an undefined order.

Although not sure why relevant, it would now be insertion order, correct?

**Comment by hlindberg** [comment]
good catch, will look at that as well

**Comment by hlindberg** [comment]
I updated the text. And since you gave thumbsup earlier I merged this.

The only possible relevance for the order (since `in` produces a boolean) is if you have an advanced reasoning about performance - it would take longer to answer if the last key is there than the first since the operation is sequential .  What you would do with this piece of information is however unclear :-)

**Comment by peterhuene** [comment]
Sorry, didn't see it was updated.  Posthumous :+1:

**Pull request merged**
