### PR TITLE
(PUP-6221) Specify SemVer and SemVerRange types

### PR DESCRIPTION
**Pull request by hlindberg**
This adds a specification of the two types SemVer and SemVerRange

### CODE REVIEW

**Comment by hlindberg** [comment]
Ping @peterhuene Can you review? (I am sure you have questions)

**Comment by peterhuene** [comment]
I'll try to get to this today, but I'm swamped with an escalation and trying to finish up delayed work from being out sick.

**Comment by hlindberg** [comment]
Thanks @peterhuene, no particular hurry...

**Comment by hlindberg** [comment]
friendly reminder ping @peterhuene

**Comment by peterhuene** [comment]
👍

**Pull request merged**
