### PR TITLE
(maint) Update CFacter to Facter File Paths

### PR DESCRIPTION
**Pull request by ferventcoder**
Remove, replace, or update all cfacter items to facter in
file path specifications.

### CODE REVIEW

**Comment by ferventcoder** [comment]
@joshcooper @kylog Prompted by reviewing #50.

**Comment by joshcooper** [comment]
@ferventcoder Looks like @kylog already has a PR up #49.

**Comment by ferventcoder** [comment]
Ha! Missed that.

**Comment by ferventcoder** [comment]
Closing b/c these changes are exactly the same as #49.

**Pull request closed without merging**
