### PR TITLE
(HI-490) Move hiera.yaml to confdir

### PR DESCRIPTION
**Pull request by kylog**

### CODE REVIEW

**Comment by hlindberg** [comment]
Reminder: we need to tag the specification repository whenever we release puppet.

**Comment by stahnma** [comment]
:+1: /cc @shrug

**Comment by ferventcoder** [comment]
Just a reminder: be sure this doesn't mean a major version bump. I followed up on the ticket. Looks like that is already being discussed, so :+1:

**Comment by kylog** [comment]
Btw, please don't merge until we get consensus on how to do this in https://tickets.puppetlabs.com/browse/HI-490. More words coming in that ticket.

**Comment by kylog** [comment]
@stahnma @shrug the more words ended up in a g-doc: https://docs.google.com/document/d/1d7PTHoMxmWL-4HXbXCR3DlZdsJk1ItgtOeRvzcslIEI/edit?ts=56b251e0. Review very much appreciated.

**Comment by kylog** [comment]
Ping @stahnma @underscorgan @hlindberg.

**Comment by hlindberg** [comment]
I think it should specify that two locations are searched, and that one is deprecated.

**Comment by underscorgan** [comment]
I'm not sure how to properly specify that, but otherwise 👍 this should be good to go / should be tagged since p-a 1.5.0 went out today.

**Comment by hlindberg** [comment]
yeah - I am behind of a spec that should go in for the SemVer and SemVerRange type before tagging.

**Comment by kylog** [comment]
@hlindberg updated to indicate that the previous locations are deprecated but searched for first.

**Comment by MikaelSmith** [comment]
This seems ready to merge?

**Comment by kylog** [comment]
Oh yeah, I forgot about this PR :)

I think it is but ping @hlindberg for a final scan.

**Pull request merged**
